# The assistant project unique identifier
assistant_id: 20241221-232154-furious-current

language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: SklearnIntentClassifier
    epochs: 50
  - name: EntitySynonymMapper
    epochs: 50
  - name: ResponseSelector
  - name: FallbackClassifier

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 50
  - name: TEDPolicy
    max_history: 5
    epochs: 50
